### ISSUE TITLE
a node in cluster of 5 segfaulted within a minute of starting up

### ISSUE THREAD

**Issue by vytas-dauksa** [aerospike/aerospike-common#8]
Steps to reproduce:
1. started asd on 5 nodes ( with no prior data )
2. wrote 3001 records in total ( saved on disk + in memory )
3. shut down all nodes
4. start all 5 nodes again
5. start writing/reading
6. One node has crashed within a minute of starting up

```
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:181) SIGSEGV received, aborting Aerospike Community Edition build 3.11.0.1 os debian8
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: found 7 frames
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 0: asd(as_sig_handle_segv+0x35) [0x48120f]
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 1: /lib/x86_64-linux-gnu/libc.so.6(+0x350e0) [0x7f854ce6d0e0]
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 2: asd(cf_queue_push+0xc) [0x5572bf]
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 3: asd(ssd_post_write+0x3f2) [0x4f9d8b]
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 4: asd(ssd_write_worker+0x12b) [0x4f9ff9]
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 5: /lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f854e0340a4]
Jan 16 2017 13:21:48 GMT: WARNING (as): (signal.c:185) stacktrace: frame 6: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f854cf2087d]
```

gdb core dump backtrace:
```
(gdb) bt
#0  cf_queue_lock (q=0x0) at src/main/citrusleaf/cf_queue.c:98
#1  cf_queue_push (q=0x0, ptr=ptr@entry=0x7f84c59fddd8) at src/main/citrusleaf/cf_queue.c:191
#2  0x00000000004f9d8b in ssd_post_write (ssd=0x7f854ca7a418, swb=0x7f848d80e740) at storage/drv_ssd.c:1400
#3  0x00000000004f9ff9 in ssd_write_worker (arg=0x7f854ca7a418) at storage/drv_ssd.c:1449
#4  0x00007f854e0340a4 in start_thread (arg=0x7f84c59fe700) at pthread_create.c:309
#5  0x00007f854cf2087d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by vytas-dauksa** [comment]
Probably linked to missing closing curly bracket in aerospike.conf ( though it worked well for awhile ):
```
namespace test {
    replication-factor 5
    memory-size 4G
    default-ttl 30d # 30 days, use 0 to never expire/evict.

    storage-engine device {
        file /opt/aerospike.dat
        filesize 4G
        data-in-memory true # Store data in memory in addition to file.
#    } # <-----
}
```
